package com.soffid.iam.addons.wsso.model;

import com.soffid.mda.annotation.Column;
import com.soffid.mda.annotation.Description;
import com.soffid.mda.annotation.Entity;
import com.soffid.mda.annotation.Identifier;
import com.soffid.mda.annotation.Nullable;

@Entity(table="SC_WSSO_DIRCTV")
@Description("Configuration directives. It can belong to a virtual server or a location")
public class Directive {
	@Identifier
	@Description("Autogenerated dentifier")
	@Column(name="DIR_ID")
	Long id;
	
	@Column (name="DIR_LOC_ID", reverseAttribute="directives", cascadeDelete=true)
	@Description("Owner location. Null means the directive applies to whole virtual server")
	@Nullable
	Location location;
	
	@Column (name="DIR_VSR_ID", reverseAttribute="directives", cascadeDelete=true)
	@Description("Owner virtual server. Null when applies to a location")
	@Nullable
	VirtualServerEntity virtualServer;
	
	@Column (name="DIR_DIR_ID", reverseAttribute="directives", cascadeDelete=true)
	@Description("Owner directive. Applies to conditional directives")
	@Nullable
	Directive parent;

	@Column (name="DIR_TAG", length=64)
	@Description ("Configuration directive name")
	String tag;
	
	@Column (name="DIR_PARAM1", length=256)
	@Description ("Configuration parameter")
	@Nullable
	String param1;
	
	@Column (name="DIR_PARAM2", length=256)
	@Description ("Configuration parameter")
	@Nullable
	String param2;
	
	@Column (name="DIR_PARAM3", length=256)
	@Description ("Configuration parameter")
	@Nullable
	String param3;
	
	@Column (name="DIR_PARAM4", length=256)
	@Description ("Configuration parameter")
	@Nullable
	String param4;
	
	@Column (name="DIR_PARAM5", length=256)
	@Description ("Configuration parameter")
	@Nullable
	String param5;
	
	ServiceProviderEntity paramServiceProvider;
	@Column (name="DIR_SPR_ID", cascadeNullify=true, reverseAttribute="references")
	@Description ("Service provider")
	@Nullable
	String serviceProvider;
	
	
	@Column (name="DIR_DIRECT", length=512)
	@Description ("Configuration parameter")
	@Nullable
	String directive;

	@Column (name="DIR_SCRIPT", length=16000)
	@Description ("Configuration scriptr")
	@Nullable
	String script;
	
}
