package com.soffid.iam.addons.wsso.model;

import com.soffid.mda.annotation.Column;
import com.soffid.mda.annotation.Description;
import com.soffid.mda.annotation.Entity;
import com.soffid.mda.annotation.Identifier;
import com.soffid.mda.annotation.Nullable;

@Entity(table="SC_WSSO_LOCATN")
@Description ("Virtual server subdirectory")
public class Location {
	@Identifier
	@Description("Autogenerated dentifier")
	@Column(name="LOC_ID")
	Long id;
	
	@Column(name="LOC_PATH")
	String path;
	
	@Column(name="LOC_REGEXP")
	Boolean regularExpression;
	
	@Column(name="LOC_VSR_ID", reverseAttribute="locations", cascadeDelete=true)
	@Nullable
	VirtualServerEntity virtualServer;
	
}
