package com.soffid.iam.addons.wsso.model;

import com.soffid.mda.annotation.Column;
import com.soffid.mda.annotation.Description;
import com.soffid.mda.annotation.Entity;
import com.soffid.mda.annotation.Identifier;
import com.soffid.mda.annotation.Nullable;

@Entity(table="SC_WSSO_SERVER")
@Description("A server stands for any WSSO server configuration\n"
		+ "A server can contain many virtual servers that perform single sign on"
		+ "against multiple legacy applications.")
public class ServerEntity {
	@Identifier
	@Description("Autogenerated dentifier")
	@Column(name="SER_ID")
	Long id;
	
	@Description ("Server name")
	@Column(name="SER_NAME", length=128)
	String name;
	
	@Nullable
	@Description ("Server description")
	@Column(name="SER_DESCRI", length=512)
	String description;
	
}
