package com.soffid.iam.addons.wsso.model;

import com.soffid.mda.annotation.Column;
import com.soffid.mda.annotation.Description;
import com.soffid.mda.annotation.Entity;
import com.soffid.mda.annotation.Identifier;

@Entity(table="SC_WSSO_SERPRO")
public class ServiceProviderEntity {
	@Identifier
	@Description("Autogenerated dentifier")
	@Column(name="SPR_ID")
	Long id;
	
	@Column(name="SPR_PUBID", length=128)
	@Description("SAML Public ID")
	String publicId;
	
	@Column(name="SPR_PRIKEY", length=1024)
	@Description("PEM encoded private key")
	String privateKey;
	
	@Column(name="SPR_CERT", length=4096)
	@Description("PEM encoded certificate chain")
	String certificate;
	
	

}
