package com.soffid.iam.addons.wsso.model;

import com.soffid.mda.annotation.Column;
import com.soffid.mda.annotation.Description;
import com.soffid.mda.annotation.Entity;
import com.soffid.mda.annotation.Identifier;

@Entity(table="SC_WSSO_VIRSER")
@Description ("A virtual server is a combination of protocol, host name and port.\n"
		+ "A virtual servier lives in a server")
public class VirtualServerEntity {
	@Identifier
	@Description("Autogenerated dentifier")
	@Column(name="VSR_ID")
	Long id;
	
	@Description("Actual server that contains this virtual server")
	@Column(name="VSR_SER_ID",reverseAttribute="virtualServers")
	ServerEntity server;
	
	@Description ("Virtual host URL")
	@Column(name="VSR_URL", length=128)
	String url;
	
	@Column(name="VSR_PRIKEY", length=1024)
	@Description("PEM encoded private key")
	String privateKey;
	
	@Column(name="VSR_CERT", length=4096)
	@Description("PEM encoded certificate chain")
	String certificate;
	

}
