#!/bin/bash
cp -vru /home/gbuades/soffid/addon-federation/web/src/main/webapp/* /home/gbuades/soffid-2.0/test/iam-console-2/work/soffid/iam-ear.ear/iam-web-*/
cp -vru /home/gbuades/soffid/addon-federation/web/src/main/resources/* /home/gbuades/soffid-2.0/test/iam-console-2/work/soffid/iam-ear.ear/iam-web-*/WEB-INF/classes

